### PR TITLE
Fix for files without filename

### PR DESCRIPTION
**Pull request by eyMarv**
Generate link for files without filename, like compressed photos.

### CODE REVIEW

**Comment by SpEcHiDe** [comment]
image

I think, you need to use this approach, instead of empty filenames ?

**Comment by eyMarv** [comment]
> image
> 
> I think, you need to use this approach, instead of empty filenames ?

Ohhh yes, which repo is this? Spechide special code?

**Comment by SpEcHiDe** [comment]
Pyrogram download_media 😐😑

**Comment by eyMarv** [comment]
> Pyrogram download_media 😐😑

Wow, will add 😄

**Pull request closed without merging**
