### PR TITLE
Need Tutorial To Host in Rdp or Vps

### PR DESCRIPTION
**Pull request by FreeModsApp**
Please Create a Tutorial To Host in Vps Or Rdp, Because i am Getting Errors

### CODE REVIEW

**Comment by TAMILVIP007** [comment]
@FreeModsApp Lel

**Comment by TAMILVIP007** [comment]
@TAMILVIP007 .

**Comment by TAMILVIP007** [comment]
@FreeModsApp .

**Comment by TAMILVIP007** [comment]
@FreeModsApp .

**Comment by TAMILVIP007** [comment]
@FreeModsApp .

**Comment by TAMILVIP007** [comment]
@FreeModsApp .

**Comment by EverythingSuckz** [comment]
@FreeModsApp Hi, please specify your issue at our support chat.

**Pull request closed without merging**
