### PR TITLE
apply env file

### PR DESCRIPTION
**Pull request by XmJwit**

### CODE REVIEW

**Comment by EverythingSuckz** [comment]
Hi @XmJwit,

Thank you for your contribution! However, it seems that the `./fsb.env` file is already defined using a volume mapping in the `docker-compose.yaml` file:
```yaml
volumes:
  - ./fsb.env:/app/fsb.env
```

The addition of the `env_file` section appears to be redundant:
```yaml
env_file:
  - path: ./fsb.env
    required: true
```

Could you please review this change and confirm if it is necessary? If there is a specific reason for this addition, please provide more context.

Thank you!

**Review by EverythingSuckz — CHANGES_REQUESTED** [review]
Hi @XmJwit,

Thank you for your contribution! However, it seems that the `./fsb.env` file is already defined using a volume mapping in the `docker-compose.yaml` file:
```yaml
volumes:
  - ./fsb.env:/app/fsb.env
```

The addition of the `env_file` section appears to be redundant:
```yaml
env_file:
  - path: ./fsb.env
    required: true
```

Could you please review this change and confirm if it is necessary? If there is a specific reason for this addition, please provide more context.

Thank you!

**Comment by XmJwit** [comment]
There is a vps, `Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1035-oracle aarch64)`, to be install TG-FileStreamBot. Firstly I used the default docker-compose.yaml file to install, but it could not find the fsb.env file! Here is the log I just rerun the config:
PixPin_2024-11-08_21-36-58


so, I try to use the docker command and all is ok :
PixPin_2024-11-08_21-46-41

Finally, I considered that the environment variable configuration file, fsb.env,  was not loaded into the container. So I used docker-compose external environment variable file loaded configuration:
```
env_file:
  - path: ./fsb.env
    required: true
```
And, as expected, it worked.
image

That's what I added.
All the best! 😄

**Review by EverythingSuckz — APPROVED** [review]
Thank you for your contribution and I'm sorry for the delay.

**Pull request merged**
