### PR TITLE
Fix for files without filename

### PR DESCRIPTION
**Pull request by GHOSTsama2503**
This doesn't fix the name that the server returns when downloading the file, but downloads. Fix this in `WebStreamer\server\stream_routes.py` if possible.

### CODE REVIEW

**Review by EverythingSuckz — COMMENTED** [review]
Thank you for your contribution, I'll be testing on your commit soon 👍

**Comment by GHOSTsama2503** [comment]
In the last commit the name with which the file is downloaded would be equal to the name of the url. The `get_name` function should get the file_name from a `pyrogram.types.Message` or from a `pyrogram.file_id.FileId`. You can replace the `else ""` in line 83 of `file_properties.py` with `else ".unknown"` if you prefer.

**Review by EverythingSuckz — APPROVED** [review]
This part looks fine

**Review by EverythingSuckz — CHANGES_REQUESTED** [review]
I got circular import when testing on this commit.
```
ImportError: cannot import name 'get_name' from partially initialized module 'WebStreamer.utils' (most likely due to a circular import) (TG-FileStreamBot\WebStreamer\utils\__init__.py)
```

Tell me if you want me to fix it.

**Comment by EverythingSuckz** [comment]
Sorry for the delay.

**Review by EverythingSuckz — APPROVED** [review]

**Pull request merged**
